# Generated by Django 4.2.4 on 2023-08-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('supervisor', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('user', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.employee')),
                ('supervisor_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.employee')),
                ('type', models.CharField(max_length=20)),
                ('hiring_price', models.CharField(default=1000, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
                ('size', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=15)),
                ('property_img', models.CharField(max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('number_of_bids', models.IntegerField()),
                ('starting_price', models.IntegerField()),
                ('increment', models.CharField(max_length=10)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.property')),
            ],
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='website.agent')),
                ('name', models.CharField(max_length=50)),
                ('relation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=20)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.property')),
            ],
            options={
                'unique_together': {('property_id', 'features')},
            },
        ),
        migrations.CreateModel(
            name='Organizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.admin')),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.auction')),
            ],
            options={
                'unique_together': {('admin_id', 'auction_id')},
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiring_price', models.CharField(max_length=50)),
                ('seller_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.user')),
                ('agent_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
            ],
            options={
                'unique_together': {('seller_id', 'agent_id')},
            },
        ),
        migrations.CreateModel(
            name='Maintains',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.property')),
                ('support_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.support')),
            ],
            options={
                'unique_together': {('property_id', 'support_id')},
            },
        ),
        migrations.CreateModel(
            name='Buys_From',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.buyer')),
            ],
            options={
                'unique_together': {('buyer_id', 'agent_id')},
            },
        ),
        migrations.CreateModel(
            name='Bids_In',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.auction')),
                ('buyer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.buyer')),
            ],
            options={
                'unique_together': {('buyer_id', 'auction_id')},
            },
        ),
        migrations.CreateModel(
            name='Agents_Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=20)),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.agent')),
            ],
            options={
                'unique_together': {('agent_id', 'client')},
            },
        ),
    ]
