# Generated by Django 4.2.4 on 2023-08-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_support_hiring_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_img',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
