# Generated by Django 4.2.2 on 2023-08-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_admin_buyer_employee_support_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
