# Generated by Django 4.2.4 on 2023-08-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_hires'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='supervisor_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
