# Generated by Django 4.2.4 on 2023-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user_user_img_alter_agent_supervisor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='supervisor_id',
            field=models.CharField(max_length=50),
        ),
    ]
