# Generated by Django 4.2.2 on 2023-08-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
