# Generated by Django 4.2.2 on 2023-08-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.CharField(max_length=10),
        ),
    ]
