# Generated by Django 4.2.2 on 2023-08-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_property_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
