# Generated by Django 4.2.2 on 2023-08-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_employee_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
