# Generated by Django 4.2.2 on 2023-08-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='supervisor_id',
            field=models.CharField(max_length=50),
        ),
    ]
