# Generated by Django 4.2.2 on 2023-08-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_agent_supervisor_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agents_clients',
            old_name='agent_id',
            new_name='agentid',
        ),
        migrations.RenameField(
            model_name='bids_in',
            old_name='auction_id',
            new_name='auctionid',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='buyer_id',
            new_name='buyerid',
        ),
        migrations.RenameField(
            model_name='buys_from',
            old_name='agent_id',
            new_name='agentid',
        ),
        migrations.RenameField(
            model_name='dependent',
            old_name='agent_id',
            new_name='agentid',
        ),
        migrations.RenameField(
            model_name='maintains',
            old_name='support_id',
            new_name='supportid',
        ),
        migrations.RenameField(
            model_name='organizes',
            old_name='auction_id',
            new_name='auctionid',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='agent_id',
            new_name='agentid',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='property_id',
            new_name='propertyid',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='agent_id',
            new_name='agentid',
        ),
        migrations.AlterUniqueTogether(
            name='agents_clients',
            unique_together={('agentid', 'client')},
        ),
        migrations.AlterUniqueTogether(
            name='bids_in',
            unique_together={('buyer_id', 'auctionid')},
        ),
        migrations.AlterUniqueTogether(
            name='buys_from',
            unique_together={('buyer_id', 'agentid')},
        ),
        migrations.AlterUniqueTogether(
            name='maintains',
            unique_together={('property_id', 'supportid')},
        ),
        migrations.AlterUniqueTogether(
            name='organizes',
            unique_together={('admin_id', 'auctionid')},
        ),
        migrations.AlterUniqueTogether(
            name='seller',
            unique_together={('seller_id', 'agentid')},
        ),
    ]
