# Generated by Django 4.2.2 on 2023-08-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_agentid_agents_clients_agent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('user', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('login', models.BooleanField()),
            ],
        ),
    ]
