# Generated by Django 4.2.2 on 2023-08-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='login',
            field=models.CharField(max_length=5),
        ),
    ]
