# Generated by Django 4.2.2 on 2023-08-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_user_property_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='property_img',
        ),
        migrations.AddField(
            model_name='property',
            name='property_img',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
